"""Output formatting for drift reports."""

from __future__ import annotations

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .comparator import DriftResult
from .runner import RunResult


def print_drift_report(drift: DriftResult, baseline: RunResult, challenger: RunResult) -> None:
    """Print a formatted drift report to the terminal."""
    console = Console()

    # Status indicator
    if drift.significant and drift.delta < 0:
        status = "[bold red]REGRESSION DETECTED[/bold red]"
        border = "red"
    elif drift.significant and drift.delta > 0:
        status = "[bold green]IMPROVEMENT DETECTED[/bold green]"
        border = "green"
    else:
        status = "[bold blue]NO SIGNIFICANT DRIFT[/bold blue]"
        border = "blue"

    # Summary panel
    lines = [
        f"  baseline:   {drift.baseline_model}",
        f"  challenger: {drift.challenger_model}",
        f"  suite:      {drift.suite_name} ({drift.n_cases} cases)",
        "",
        f"  Status: {status}",
        "",
        f"  Baseline mean:    {drift.baseline_mean:.4f}",
        f"  Challenger mean:  {drift.challenger_mean:.4f}",
        f"  Delta:            {drift.delta:+.4f} ({drift.delta_pct:+.1f}%)",
        f"  p-value:          {drift.p_value:.6f}",
        f"  95% CI:           [{drift.ci_lower:+.4f}, {drift.ci_upper:+.4f}]",
        "",
        f"  Regressed cases:  {len(drift.regressed_cases)}",
        f"  Improved cases:   {len(drift.improved_cases)}",
    ]

    console.print(Panel("\n".join(lines), title="[bold]Rift Drift Report[/bold]", border_style=border))

    # Case-level detail table for regressions
    if drift.regressed_cases:
        table = Table(title="Regressed Cases", show_lines=True)
        table.add_column("Case #", style="bold", width=8)
        table.add_column("Baseline Score", width=15)
        table.add_column("Challenger Score", width=15)
        table.add_column("Delta", width=12)
        table.add_column("Input (truncated)", max_width=50)

        for idx in drift.regressed_cases[:10]:  # Show top 10
            b_score = baseline.cases[idx].score
            c_score = challenger.cases[idx].score
            d = c_score - b_score
            input_trunc = baseline.cases[idx].input_text[:80].replace("\n", " ")
            table.add_row(
                str(idx),
                f"{b_score:.4f}",
                f"{c_score:.4f}",
                f"[red]{d:+.4f}[/red]",
                input_trunc,
            )

        console.print(table)


def generate_markdown_report(drift: DriftResult, baseline: RunResult, challenger: RunResult) -> str:
    """Generate a markdown drift report suitable for blog posts."""
    if drift.significant and drift.delta < 0:
        status_emoji = "🔴"
        status_text = "Regression Detected"
    elif drift.significant and drift.delta > 0:
        status_emoji = "🟢"
        status_text = "Improvement Detected"
    else:
        status_emoji = "🔵"
        status_text = "No Significant Drift"

    lines = [
        f"# Rift Drift Report: {drift.baseline_model} vs {drift.challenger_model}",
        "",
        f"**Suite:** {drift.suite_name} ({drift.n_cases} cases)  ",
        f"**Status:** {status_emoji} {status_text}  ",
        f"**Generated by [Rift](https://github.com/shahcolate/rift)**",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Baseline mean | {drift.baseline_mean:.4f} |",
        f"| Challenger mean | {drift.challenger_mean:.4f} |",
        f"| Delta | {drift.delta:+.4f} ({drift.delta_pct:+.1f}%) |",
        f"| p-value | {drift.p_value:.6f} |",
        f"| 95% CI | [{drift.ci_lower:+.4f}, {drift.ci_upper:+.4f}] |",
        f"| Regressed cases | {len(drift.regressed_cases)} / {drift.n_cases} |",
        f"| Improved cases | {len(drift.improved_cases)} / {drift.n_cases} |",
        "",
    ]

    if drift.regressed_cases:
        lines.extend([
            "## Regressed Cases",
            "",
            "| Case | Baseline | Challenger | Delta | Input |",
            "|------|----------|------------|-------|-------|",
        ])
        for idx in drift.regressed_cases[:20]:
            b = baseline.cases[idx]
            c = challenger.cases[idx]
            d = c.score - b.score
            inp = b.input_text[:60].replace("\n", " ").replace("|", "\\|")
            lines.append(f"| {idx} | {b.score:.4f} | {c.score:.4f} | {d:+.4f} | {inp} |")
        lines.append("")

    return "\n".join(lines)
